### ISSUE TITLE
Maybe you can try it with Android 11

### ISSUE THREAD

**Issue by hipteromyini** [lx200916/iCS_Importer#1]

**Comment by lx200916** [comment]
Already Tested on Emulators since I have no device running API 30, looks fine for now.
BTW is anything functions unexceptedly?

**Comment by hipteromyini** [comment]
So ，Why we two Chinese are speaking English.

**Comment by hipteromyini** [comment]
李翔大佬nb

**Comment by lx200916** [comment]
> 李翔大佬nb
> 

az...
